
import java.awt.Canvas;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Graphics;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicArrowButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kolbusz
 */
public class subsetGUI extends javax.swing.JFrame {

    /**
     * Creates new form subsetGUI
     */
    public subsetGUI() {
        initComponents();
        drawButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        populationSize = new javax.swing.JSpinner();
        targetSum = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        individualTolerance = new javax.swing.JSpinner();
        mutationPropability = new javax.swing.JSpinner();
        mutationNumberInStep = new javax.swing.JSpinner();
        startButton = new javax.swing.JButton();
        importDataCSVBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        propabilityOfSettingGene = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        maxIterationsNumber = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        maxNumberSetValue = new javax.swing.JSpinner();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Problem sumy podzbiory - Alogrytm Genetyczny");
        setBackground(new java.awt.Color(126, 164, 17));
        setForeground(java.awt.Color.white);
        setMaximumSize(new java.awt.Dimension(328, 508));
        setMinimumSize(new java.awt.Dimension(328, 508));

        populationSize.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(100), Integer.valueOf(1), null, Integer.valueOf(1)));
        populationSize.setBorder(null);

        targetSum.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        targetSum.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        targetSum.setBorder(null);

        jLabel2.setText("ROZMIAR POPULACJI");

        jLabel4.setText("Suma docelowa");

        jLabel5.setText("<html>Tolerancja dla osobnika <b>[%]</b></html>");

        jLabel6.setText("<html> Prawdopodobieństwo<br/> mutacji <b>[%]</b></html>");

        jLabel7.setText("<html>\nMaksymalna ilość mutacji<br/>\nw kroku\n</html>");

        individualTolerance.setModel(new javax.swing.SpinnerNumberModel(50, 0, 100, 1));

        mutationPropability.setModel(new javax.swing.SpinnerNumberModel(50.0d, 0.0d, 100.0d, 0.01d));

        mutationNumberInStep.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(5), Integer.valueOf(0), null, Integer.valueOf(1)));

        startButton.setBackground(new java.awt.Color(76, 59, 77));
        startButton.setForeground(new java.awt.Color(201, 237, 220));
        startButton.setText("Start - uruchom algorytm");

        importDataCSVBtn.setBackground(new java.awt.Color(76, 59, 77));
        importDataCSVBtn.setForeground(new java.awt.Color(201, 237, 220));
        importDataCSVBtn.setText("Importuj dane z pliku CSV");
        importDataCSVBtn.setBorderPainted(false);
        importDataCSVBtn.setFocusPainted(false);

        jLabel8.setText("<html>Maksymalna ilość iteracji</html>");

        propabilityOfSettingGene.setModel(new javax.swing.SpinnerNumberModel(30, 0, 100, 1));

        jLabel9.setText("<html>Prawdopodobieństwo ustawienia genu osobnika populacji początkowej <b>[%]</b></html>");

        maxIterationsNumber.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(30), Integer.valueOf(1), null, Integer.valueOf(1)));

        jLabel10.setText("<html>\nMaksymalna wartość elementu<br/>w zbiorze wejściowym\n</html>");

        maxNumberSetValue.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        exitBtn.setBackground(new java.awt.Color(76, 59, 77));
        exitBtn.setForeground(new java.awt.Color(201, 237, 220));
        exitBtn.setText("Zamknij aplikację");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(importDataCSVBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(263, 263, 263)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(targetSum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(populationSize)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel8))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(maxIterationsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(propabilityOfSettingGene, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                        .addGap(93, 93, 93)))
                                .addGap(179, 179, 179)))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(maxNumberSetValue, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(individualTolerance, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(mutationPropability, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                            .addComponent(mutationNumberInStep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(exitBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(importDataCSVBtn)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(populationSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(targetSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxNumberSetValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(individualTolerance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mutationPropability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mutationNumberInStep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(propabilityOfSettingGene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxIterationsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(startButton)
                .addGap(18, 18, 18)
                .addComponent(exitBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton importDataCSVBtn;
    private javax.swing.JSpinner individualTolerance;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner maxIterationsNumber;
    private javax.swing.JSpinner maxNumberSetValue;
    private javax.swing.JSpinner mutationNumberInStep;
    private javax.swing.JSpinner mutationPropability;
    private javax.swing.JSpinner populationSize;
    private javax.swing.JSpinner propabilityOfSettingGene;
    private javax.swing.JButton startButton;
    private javax.swing.JSpinner targetSum;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the individualTolerance
     */
    public javax.swing.JSpinner getIndividualTolerance() {
        return individualTolerance;
    }

    /**
     * @return the populationSize
     */
    public javax.swing.JSpinner getPopulationSize() {
        return populationSize;
    }

    /**
     * @return the targetSum
     */
    public javax.swing.JSpinner getTargetSum() {
        return targetSum;
    }

    /**
     * @return the mutatioNumberInStep
     */
    public javax.swing.JSpinner getMutationNumberInStep() {
        return mutationNumberInStep;
    }

    /**
     * @return the mutationPropability
     */
    public javax.swing.JSpinner getMutationPropability() {
        return mutationPropability;
    }

    /**
     * @return the startButton
     */
    public javax.swing.JButton getStartButton() {
        return startButton;
    }

    /**
     * @return the importDataCSVBtn
     */
    public javax.swing.JButton getImportDataCSVBtn() {
        return importDataCSVBtn;
    }

    /**
     * @return the maxIterationsNumber
     */
    public javax.swing.JSpinner getMaxIterationsNumber() {
        return maxIterationsNumber;
    }

    /**
     * @return the propabilityOfSettingGene
     */
    public javax.swing.JSpinner getPropabilityOfSettingGene() {
        return propabilityOfSettingGene;
    }

    /**
     * @return the maxNumberSetValue
     */
    public javax.swing.JSpinner getMaxNumberSetValue() {
        return maxNumberSetValue;
    }

    /**
     * @return the exitBtn
     */
    public javax.swing.JButton getExitBtn() {
        return exitBtn;
    }
    
    public Container getFrame(){
        return this.getContentPane();
    }
    
    public void drawButtons(){

            ImageIcon icon = new ImageIcon("icon.png");
            jLabel2.setIcon(icon);
            
            Component c = populationSize.getEditor().getComponent(0);
            c.setBackground(Color.red);
            
             InputStream is;

            Font font;
            try {
                is = new FileInputStream(new File("futura.ttf"));
                font = Font.createFont(Font.TRUETYPE_FONT, is);
                startButton.setFont(font);
                startButton.setFont(startButton.getFont().deriveFont(1, (float)18.0));
                 Component[] cs = populationSize.getComponents();
            for(int i=0; i < cs.length; i++){
                if(cs[i] instanceof BasicArrowButton){
                    cs[i].setBackground(Color.red);
                    cs[i].getGraphics().setColor(Color.red);
                    cs[i].setForeground(Color.yellow);
                    
                }
            }
            } catch (FontFormatException ex) {
                Logger.getLogger(subsetGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(subsetGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            catch (IOException ex) {
                Logger.getLogger(subsetGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            

            getContentPane().setBackground(Color.red);
            
            JLabel lbl = new JLabel(icon);
            lbl.setSize(200,200);
            lbl.setLocation(-50,-70);
                
            getContentPane().add(lbl);
            getContentPane().repaint();
    }
}
